name: f_users
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  uuid: ^4.5.1

  flutter_svg: ^2.0.14
  sqflite: ^2.0.0+4

  sqflite_common_ffi: ^2.0.0
  sqflite_common_ffi_web: ^0.4.5+3

  provider: ^6.0.3
  path_provider: ^2.0.8
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/
